run:
  timeout: 5m
  tests: true
  build-tags: []
  skip-dirs:
    - vendor
    - testdata

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - unconvert
    - unparam
    - gosec
    - gocritic
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
  
  gofmt:
    simplify: true
  
  revive:
    severity: warning
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: package-comments
        severity: warning
  
  gosec:
    excludes:
      - G104  # Audit errors not checked (we use errcheck)
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
